# Generated by Django 3.2.9 on 2021-11-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200, verbose_name='测试内容')),
            ],
            options={
                'verbose_name': '测试类',
                'verbose_name_plural': '测试类',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.CharField(default='https://github.com/MengZumeng', max_length=255, verbose_name='图片地址'),
        ),
    ]
