# Generated by Django 3.2.9 on 2021-12-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_is_top'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Silian',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
